In [1]:
from __future__ import print_function
import torch

In [2]:
#张量就是多维数组
#构造一个随机初始化的矩阵
x = torch.rand(5,3)
print(x)

tensor([[4.9284e-01, 5.1743e-01, 1.4872e-01],
        [3.0702e-01, 3.7694e-04, 3.2635e-01],
        [9.8423e-01, 7.6725e-01, 5.0013e-01],
        [1.1899e-01, 1.9294e-01, 3.0567e-01],
        [2.7404e-01, 5.7456e-01, 5.2955e-01]])


In [3]:
#构造一个初始化为0的矩阵,数据类型为long
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [4]:
#直接给定数据构造张量
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [5]:
x = x.new_ones(5,3,dtype=torch.double)
print(x)
#构建与输入张量同样大小的张量
x = torch.randn_like(x,dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.2939, -1.7213,  0.4729],
        [-0.8624, -0.4417,  0.1022],
        [ 0.3530,  0.6652, -0.3936],
        [-0.8312,  0.1587,  1.2410],
        [-0.3177, -0.8980,  1.0872]])


In [6]:
#获取张量的大小，结果torch.Size是个元组，支持元组相关操作
print(x.size())

torch.Size([5, 3])


In [5]:
#张量相加
x = torch.zeros(5,3)
y = torch.ones(5,3)
print(x + y)
#使用torch.add()函数
print(torch.add(x,y))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [6]:
#输出相加的张量也可以：
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [7]:
#把x加到y上,所有改变tensor内容的操作都会在方法名后加一个下划线 '_'
y.add_(x)
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [8]:
#可以使用numpy所有标准操作，比如切片
print(x[:,1])  #输出第二列

tensor([0., 0., 0., 0., 0.])


In [9]:
#可以用torch.view来调整张量大小
a = torch.randn(4,4)
b = a.view(16)
c = a.view(-1,8)  #-1表示从其他维度推断
print(a.size(),b.size(),c.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [10]:
#如果有一个张量，可以使用.item（）得到一个Python数
d = torch.randn(1)
print(d)
print(d.item())

tensor([-0.2623])
-0.2622828781604767


In [11]:
#numpy和tensor之间互相转换,numpy和tensor是共享储存空间的，修改一个会导致另一个也被修改
a = torch.ones(5)
b = a.numpy()
print(a,b)


tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]


In [12]:
#修改a,b也会跟随改变
a.add_(1)
print(a,b)

tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]


In [13]:
import numpy as np
a = np.ones(5)
b = torch.Tensor(a)  #numpy转tensor、


CPU上的所有Tensor除了CharTensor，都支持与numpy之间的互相转换
CUDA Tensor 通过.to可以被转移到任何设备

In [14]:
x = torch.randn(5,5)
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x,device = device)
    x = x.to(device)   #把 X 从CPU移动到GPU
    z = x + y
    print(z)
    print(z.to("cpu",torch.double)) #把 Z 从GPU移动到CPU

tensor([[-0.1294,  1.8767,  0.9693, -0.7512,  1.2836],
        [-0.5177,  0.1082,  1.7519, -0.2295,  0.9434],
        [ 1.9005,  0.1620,  2.6186,  0.6424, -1.2304],
        [ 0.8798,  0.3009,  0.9205,  1.7988,  1.4602],
        [ 2.0656,  0.0195,  0.5517,  1.8487,  0.3720]], device='cuda:0')
tensor([[-0.1294,  1.8767,  0.9693, -0.7512,  1.2836],
        [-0.5177,  0.1082,  1.7519, -0.2295,  0.9434],
        [ 1.9005,  0.1620,  2.6186,  0.6424, -1.2304],
        [ 0.8798,  0.3009,  0.9205,  1.7988,  1.4602],
        [ 2.0656,  0.0195,  0.5517,  1.8487,  0.3720]], dtype=torch.float64)


In [16]:
a=torch.Tensor([[1,2,3],[4,5,6],[7,8,9]])
b=torch.Tensor([[10,12,13],[14,15,16],[17,18,19]])
torch.mm(a,b)

tensor([[ 89.,  96., 102.],
        [212., 231., 246.],
        [335., 366., 390.]])