# 前向传播

In [14]:
import torch
x = torch.ones(2)
print(x)
x.requires_grad

tensor([1., 1.])


False

In [15]:
x.requires_grad = True
x

tensor([1., 1.], requires_grad=True)

In [16]:
z = 4*x
z

tensor([4., 4.], grad_fn=<MulBackward0>)

In [17]:
#y等于z的范数值0
y=z.norm()
y

tensor(5.6569, grad_fn=<NormBackward0>)

# 反向传播

In [18]:
#y.backward()
y.backward()
x.grad

tensor([2.8284, 2.8284])