In [21]:
import torch

In [22]:
x = torch.ones(2,2,requires_grad = True)  #创建一个张量，并记录他的运算过程（requires_grad = True）。
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [23]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [24]:
print(y.grad_fn)

In [25]:
z = y * y * 3
out = z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [26]:
a = torch.rand(2,2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)  #记录a的计算过程
print(a.requires_grad)
b = (a * a).sum()
print(a.grad_fn)  #a还没有进行计算，所以结果为None
print(b.grad_fn)

False
True
None


In [27]:
out.backward()
print(out)

tensor(27., grad_fn=<MeanBackward0>)


In [28]:
#打印x的梯度
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [29]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([1099.7539,  439.7245, -588.8167], grad_fn=<MulBackward0>)
